pruning_parameters:
  enable_pruning: true
  epsilon: 0.015
  pruning_method: pdp
  sparsity: 0.8
  temperature: 1.0e-05
  structured_pruning: false
quantization_parameters:
  default_integer_bits: 0.
  default_fractional_bits: 7.
  enable_quantization: true
  hgq_gamma: 0.0003
  layer_specific: []
  use_high_granularity_quantization: false
training_parameters:
  batch_size: 256
  cosine_tmax: 200
  epochs: 100
  fine_tuning_epochs: 20
  gamma: 0.1
  l2_decay: 0.0001
  label_smoothing: 0.0
  lr: 0.01
  lr_schedule: cosine
  milestones:
  - -1
  - -1
  momentum: 0.9
  optimizer: sgd
  plot_frequency: 100
  pretraining_epochs: 16
  pruning_first: false
  rewind: never
  rounds: 1
  save_weights_epoch: -1
  threshold_decay: 0.
